project:
  type: website
  output-dir: "docs"
language:
  title-block-author-single: "Auteur"
author:
  - name: "D<sup>r</sup> Philippe MICHEL"
    orcid: "0000-0003-2392-7186"
    email: "philippe.michel@ght-novo.fr"
    role: "Statisticien"
    affiliations:
      name: "USRC - Hôpital NOVO"
      city: "Pontoise"
      department: "Unité de Soutien à la Recherche Clinique"
title-block-banner: "#26474a"
title-block-banner-color: white
lang: fr
website:
  title: "PETRUS Validations"
  search:
    location: sidebar
    type: textbox
  page-footer:
    left: "Copyright 2025 USRC--- Hôpital NOVO"
    right:
      - icon: github
        href: https://github.com/philippemichel
      - icon: twitter
        href: https://twitter.com/PhiippeMICHEL
      - icon: mailbox
        text: mail
        href: mailto:docphilmstat@gmail.com
  sidebar:
    style: "docked"
    pinned: true
    search: true
    contents:
      - section: "PETRUS"
        contents:
          - index.qmd
  open-graph:
    locale: fr_FR
    site-name: PETRUS Validations
format:
  html:
    page-layout: full
    highlight-style: ayu
    code-fold: true
    theme:
      light:
        - sandstone
      dark: cyborg
    fontsize: 1.2em
    toc: true
    warning: false
    message: false
    eval: true


